export const list = {
  trending: [
    "All", 
    "Bitcoin", 
    "Micro Strategy", 
    "Crypto Prices", 
    "Ethereum", 
    "Crypto Reserve", 
    "Market",
    "Airdrops", 
    "Solana", 
  ],
  new: [
    "All", 
    "Ethereum", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Crypto Prices", 
    "Solana", 
    "Bitcoin", 
    "Market",
  ],
  politics: [
    "All", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Crypto Prices", 
    "Ethereum", 
    "Market",
    "Bitcoin", 
    "Solana", 
    "Airdrops", 
  ],
  sports: [
    "All", 
    "Bitcoin", 
    "Solana", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Crypto Reserve", 
    "Crypto Prices", 
    "Market",
  ],
  crypto: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ],
  tech: [
    "All", 
    "Ethereum", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Bitcoin", 
    "Airdrops", 
    "Crypto Prices", 
    "Solana", 
    "Market",
  ],
  culture: [
    "All", 
    "Bitcoin", 
    "Ethereum", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Crypto Prices", 
    "Solana", 
    "Market",
  ],
  world: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ],
  economy: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ],
  trump: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ],
  Elections: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ],
  Mentions: [
    "All", 
    "Crypto Prices", 
    "Bitcoin", 
    "Crypto Reserve", 
    "Micro Strategy", 
    "Airdrops", 
    "Ethereum", 
    "Solana", 
    "Market",
  ]
}
