import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const chakra_petch = Chakra_Petch({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-chakra-petch",
})

export const metadata: Metadata = {
  title: "VRAID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chakra_petch.variable} antialiased `}
      >
        <Header />
        <main className="max-w-[1440px] mx-auto mt-[150px] font-chakra-petch">
          {children}
        </main>
      </body>
    </html>
  );
}
